### ISSUE TITLE
Issue: Unexpected Redirection and Response After Submitting Recipe

### ISSUE THREAD

**Issue by shouryamanekar** [NightwavesStudios/CulinaryShare#15]
# Issue: Unexpected Redirection and Response After Submitting Recipe

## Description
After submitting a recipe, the page is directed to an unexpected URL 

```
(`https://script.googleusercontent.com/macros/echo?user_content_key=zkWpHITtqXnn_S1S5US2-4i8CkmDXVy9KN_h8VecglB3HBbq5UB5m954Vrn8nJ2kpW4Gqu58FJyZzsTKDipw-RdPVvnyXHZZm5_BxDlH2jW0nuo2oDemN9CCS2h10ox_1xSncGQajx_ryfhECjZEnN_AHzlnjQbGB7JVbe8WGHby8-DSQcw720CMKFcEfDP8zlqYC27KfHUkI_BGIxDVCazzyVbOddKaNyCrUtUE4PykliFgWpO_kg&lib=MzeTQwLgME84zyBJ804e43u2t-2Q6bcGy`), 
```

and the page shows 

```
`{"result":"success","row":12}` 
```

instead of reverting to the home page, recipe page, or any other page. Additionally, there is no popup indicating that the recipe is added. Upon checking the `/recipes` page, the recipe is not even added.

## Steps to Reproduce
1. Navigate to the contribute page.
2. Fill out the required information for a new recipe.
3. Submit the form to contribute the recipe.

## Expected Behavior
After submitting a recipe, the page should redirect to an appropriate page (e.g., home page or recipe page), and there should be a success notification or popup indicating that the recipe is added.

## Actual Behavior
The page is redirected to an unexpected URL, and the response `{"result":"success","row":12}` is displayed. No popup is shown, and upon checking the `/recipes` page, the recipe is not added.

## Screenshots
![image](https://github.com/NightwavesStudios/CulinaryShare/assets/72398499/9b33985d-72c8-404d-a79d-44cf551a72de)

## Environment
- Operating System: Windows
- Browser: Chrome

## Labels
- bug
- backend

**Comment by NightwavesStudios** [comment]
This is because your browser is blocking the redirect to the home screen. I do not know why this is. Do you have a popup blocker?
